#ifndef UART_REGS_H
#define UART_REGS_H

#include "../example_srtructure/tms570_common.h"

/* Base addresses for SCI modules */
#define TMS570_SCI_LIN_1_BASE_ADDR                ((tms570_reg*)0xFFF7E400)
#define TMS570_SCI_LIN_2_BASE_ADDR                ((tms570_reg*)0xFFF7E600)
#define TMS570_SCI_LIN_3_BASE_ADDR                ((tms570_reg*)0xFFF7E500)

/* SCI Register Offsets */
#define TMS570_SCI_GCR0                      (0x00 / sizeof(tms570_reg))  /* SCI Global Control Register 0 */
#define TMS570_SCI_GCR1                      (0x04 / sizeof(tms570_reg))  /* SCI Global Control Register 1 */
#define TMS570_SCI_GCR2                      (0x08 / sizeof(tms570_reg))  /* SCI Global Control Register 2 */
#define TMS570_SCI_SET_INT                   (0x0C / sizeof(tms570_reg))  /* SCI Set Interrupt Register 0 */
#define TMS570_SCI_CLEAR_INT                 (0x10 / sizeof(tms570_reg))  /* SCI Clear Interrupt Register */
#define TMS570_SCI_SET_INT_LVL               (0x14 / sizeof(tms570_reg))  /* SCI Set Interrupt Level Register */
#define TMS570_SCI_CLEAR_INT_LVL             (0x18 / sizeof(tms570_reg))  /* SCI Clear Interrupt Level Register */
#define TMS570_SCI_FLR                       (0x1C / sizeof(tms570_reg))  /* SCI Flags Register */
#define TMS570_SCI_INT_VECT_0                (0x20 / sizeof(tms570_reg))  /* SCI Interrupt Vector Offset 0 */
#define TMS570_SCI_INT_VECT_1                (0x24 / sizeof(tms570_reg))  /* SCI Interrupt Vector Offset 1 */
#define TMS570_SCI_FORMAT                    (0x28 / sizeof(tms570_reg))  /* SCI Format Control Register */
#define TMS570_SCI_BRS                       (0x2C / sizeof(tms570_reg))  /* Baud Rate Selection Register */
#define TMS570_SCI_ED                        (0x30 / sizeof(tms570_reg))  /* Receiver Emulation Data Buffer */
#define TMS570_SCI_RD                        (0x34 / sizeof(tms570_reg))  /* Receiver Data Buffer */
#define TMS570_SCI_TD                        (0x38 / sizeof(tms570_reg))  /* Transmit Data Buffer */
#define TMS570_SCI_PIO_0                     (0x3C / sizeof(tms570_reg))  /* SCI Pin I/O Control Register 0 */
#define TMS570_SCI_PIO_1                     (0x40 / sizeof(tms570_reg))  /* SCI Pin I/O Control Register 1 */
#define TMS570_SCI_PIO_2                     (0x44 / sizeof(tms570_reg))  /* SCI Pin I/O Control Register 2 */
#define TMS570_SCI_PIO_3                     (0x48 / sizeof(tms570_reg))  /* SCI Pin I/O Control Register 3 */
#define TMS570_SCI_PIO_4                     (0x4C / sizeof(tms570_reg))  /* SCI Pin I/O Control Register 4 */
#define TMS570_SCI_PIO_5                     (0x50 / sizeof(tms570_reg))  /* SCI Pin I/O Control Register 5 */
#define TMS570_SCI_PIO_6                     (0x54 / sizeof(tms570_reg))  /* SCI Pin I/O Control Register 6 */
#define TMS570_SCI_PIO_7                     (0x58 / sizeof(tms570_reg))  /* SCI Pin I/O Control Register 7 */
#define TMS570_SCI_PIO_8                     (0x5C / sizeof(tms570_reg))  /* SCI Pin I/O Control Register 8 */
#define TMS570_LIN_COMPARE                   (0x60 / sizeof(tms570_reg))  /* LIN Compare Register */
#define TMS570_LIN_RD_0                      (0x64 / sizeof(tms570_reg))  /* LIN Receive Buffer 0 Register */
#define TMS570_LIN_RD_1                      (0x68 / sizeof(tms570_reg))  /* LIN Receive Buffer 1 Register */
#define TMS570_LIN_MASK                      (0x6C / sizeof(tms570_reg))  /* LIN Mask Register */
#define TMS570_LIN_ID                        (0x70 / sizeof(tms570_reg))  /* LIN Identification Register */
#define TMS570_LIN_TD_0                      (0x74 / sizeof(tms570_reg))  /* LIN Transmit Buffer 0 */
#define TMS570_LIN_TD_1                      (0x78 / sizeof(tms570_reg))  /* LIN Transmit Buffer 1 */
#define TMS570_MBRS                          (0x7C / sizeof(tms570_reg))  /* Maximum Baud Rate Selection Register */
#define TMS570_IODFTCTRL                     (0x90 / sizeof(tms570_reg))  /* Input/Output Error Enable Register */

/* Register Masks */
#define TMS570_SCI_GCR0_MASK                 (0x00000001)
#define TMS570_SCI_GCR1_MASK                 (0x03033FFF)
#define TMS570_SCI_GCR2_MASK                 (0x00030101)
#define TMS570_SCI_SET_INT_MASK              (0xFF0723D3)
#define TMS570_SCI_CLEAR_INT_MASK            (0xFF0723D3)
#define TMS570_SCI_SET_INT_LVL_MASK          (0xFF0423D3)
#define TMS570_SCI_CLEAR_INT_LVL_MASK        (0xFF0423D3)
#define TMS570_SCI_FLR_MASK                  (0xFF007FDF)
#define TMS570_SCI_INT_VECT_0_MASK           (0x0000001F)
#define TMS570_SCI_INT_VECT_1_MASK           (0x0000001F)
#define TMS570_SCI_FORMAT_MASK               (0x00070007)
#define TMS570_SCI_BRS_MASK                  (0x7FFFFFFF)
#define TMS570_SCI_ED_MASK                   (0x000000FF)
#define TMS570_SCI_RD_MASK                   (0x000000FF)
#define TMS570_SCI_TD_MASK                   (0x000000FF)
#define TMS570_SCI_PIO_0_MASK                (0x00000006)
#define TMS570_SCI_PIO_1_MASK                (0x00000006)
#define TMS570_SCI_PIO_2_MASK                (0x00000006)
#define TMS570_SCI_PIO_3_MASK                (0x00000006)
#define TMS570_SCI_PIO_4_MASK                (0x00000006)
#define TMS570_SCI_PIO_5_MASK                (0x00000006)
#define TMS570_SCI_PIO_6_MASK                (0x00000006)
#define TMS570_SCI_PIO_7_MASK                (0x00000006)
#define TMS570_SCI_PIO_8_MASK                (0x00000006)
#define TMS570_LIN_COMPARE_MASK              (0x00000307)
#define TMS570_LIN_RD_0_MASK                 (0xFFFFFFFF)
#define TMS570_LIN_RD_1_MASK                 (0xFFFFFFFF)
#define TMS570_LIN_MASK_MASK                 (0x00FF00FF)
#define TMS570_LIN_ID_MASK                   (0x00FFFFFF)
#define TMS570_LIN_TD_0_MASK                 (0xFFFFFFFF)
#define TMS570_LIN_TD_1_MASK                 (0xFFFFFFFF)
#define TMS570_MBRS_MASK                     (0x00001FFF)
#define TMS570_IODFTCTRL_MASK                (0xFF1F0F03)

/* GCR0 Fields */
#define TMS570_SCI_GCR0_RESET_BIT_OFFSET     (0)

#define TMS570_SCI_GCR0_RESET_BIT_LEN        (1)

/* GCR1 Fields */
#define TMS570_SCI_GCR1_COMM_MODE_OFFSET      (0)
#define TMS570_SCI_GCR1_TIMING_MODE_OFFSET    (1)
#define TMS570_SCI_GCR1_PARITY_ENA_OFFSET     (2)
#define TMS570_SCI_GCR1_PARITY_OFFSET         (3)
#define TMS570_SCI_GCR1_STOP_OFFSET           (4)
#define TMS570_SCI_GCR1_CLOCK_OFFSET          (5)
#define TMS570_SCI_GCR1_LIN_MODE_OFFSET       (6)
#define TMS570_SCI_GCR1_SWnRST_OFFSET         (7)
#define TMS570_SCI_GCR1_SLEEP_OFFSET          (8)
#define TMS570_SCI_GCR1_ADAPT_OFFSET          (9)
#define TMS570_SCI_GCR1_MBUF_OFFSET           (10)
#define TMS570_SCI_GCR1_CTYPE_OFFSET          (11)
#define TMS570_SCI_GCR1_HGEN_CTRL_OFFSET      (12)
#define TMS570_SCI_GCR1_STOP_EXT_FRAME_OFFSET (13)
#define TMS570_SCI_GCR1_LOOP_BACK_OFFSET      (16)
#define TMS570_SCI_GCR1_CONT_OFFSET           (17)
#define TMS570_SCI_GCR1_RX_ENA_OFFSET         (24)
#define TMS570_SCI_GCR1_TX_ENA_OFFSET         (25)

#define TMS570_SCI_GCR1_COMM_MODE_BIT_LEN     (1)
#define TMS570_SCI_GCR1_TIMING_MODE_BIT_LEN   (1)
#define TMS570_SCI_GCR1_PARITY_ENA_BIT_LEN    (1)
#define TMS570_SCI_GCR1_PARITY_BIT_LEN        (1)
#define TMS570_SCI_GCR1_STOP_BIT_LEN          (1)
#define TMS570_SCI_GCR1_CLOCK_BIT_LEN         (1)
#define TMS570_SCI_GCR1_LIN_MODE_BIT_LEN      (1)
#define TMS570_SCI_GCR1_SWnRST_BIT_LEN        (1)
#define TMS570_SCI_GCR1_SLEEP_BIT_LEN         (1)
#define TMS570_SCI_GCR1_ADAPT_BIT_LEN         (1)
#define TMS570_SCI_GCR1_MBUF_BIT_LEN          (1)
#define TMS570_SCI_GCR1_CTYPE_BIT_LEN         (1)
#define TMS570_SCI_GCR1_HGEN_CTRL_BIT_LEN     (1)
#define TMS570_SCI_GCR1_STOP_EXT_FRAME_BIT_LEN (1)
#define TMS570_SCI_GCR1_LOOP_BACK_BIT_LEN     (1)
#define TMS570_SCI_GCR1_CONT_BIT_LEN          (1)
#define TMS570_SCI_GCR1_RX_ENA_BIT_LEN        (1)
#define TMS570_SCI_GCR1_TX_ENA_BIT_LEN        (1)


/* GCR2 Fields */
#define TMS570_SCI_GCR2_POWERDOWN_OFFSET      (0)
#define TMS570_SCI_GCR2_GEN_WU_OFFSET         (8)
#define TMS570_SCI_GCR2_SC_OFFSET             (16)
#define TMS570_SCI_GCR2_CC_OFFSET             (17)

#define TMS570_SCI_GCR2_POWERDOWN_BIT_LEN       (1)
#define TMS570_SCI_GCR2_GEN_WU_BIT_LEN       (1)
#define TMS570_SCI_GCR2_SC_BIT_LEN       (1)
#define TMS570_SCI_GCR2_CC_BIT_LEN       (1)


/* SET_INT Fields */
#define TMS570_SCI_SET_INT_SET_BRKDT_INT_OFFSET (0)
#define TMS570_SCI_SET_INT_SET_WAKEUP_INT_OFFSET (1)
#define TMS570_SCI_SET_INT_SET_TIMEOUT_INT_OFFSET (4)
#define TMS570_SCI_SET_INT_SET_TOAWUS_INT_OFFSET (6)
#define TMS570_SCI_SET_INT_SET_TOA3WUS_INT_OFFSET (7)
#define TMS570_SCI_SET_INT_SET_TX_INT_OFFSET (8)
#define TMS570_SCI_SET_INT_SET_RX_INT_OFFSET (9)
#define TMS570_SCI_SET_INT_SET_ID_INT_OFFSET (13)
#define TMS570_SCI_SET_INT_SET_TX_DMA_OFFSET (16)
#define TMS570_SCI_SET_INT_SET_RX_DMA_OFFSET (17)
#define TMS570_SCI_SET_INT_SET_RX_DMA_ALL_OFFSET (18)
#define TMS570_SCI_SET_INT_SET_PE_INT_OFFSET (24)
#define TMS570_SCI_SET_INT_SET_OE_INT_OFFSET (25)
#define TMS570_SCI_SET_INT_SET_FE_INT_OFFSET (26)
#define TMS570_SCI_SET_INT_SET_NRE_INT_OFFSET (27)
#define TMS570_SCI_SET_INT_SET_ISFE_INT_OFFSET (28)
#define TMS570_SCI_SET_INT_SET_CE_INT_OFFSET (29)
#define TMS570_SCI_SET_INT_SET_PBE_INT_OFFSET (30)
#define TMS570_SCI_SET_INT_SET_BE_INT_OFFSET (31)

#define TMS570_SCI_SET_INT_SET_BRKDT_INT_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_WAKEUP_INT_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_TIMEOUT_INT_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_TOAWUS_INT_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_TOA3WUS_INT_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_TX_INT_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_RX_INT_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_ID_INT_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_TX_DMA_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_RX_DMA_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_RX_DMA_ALL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_PE_INT_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_OE_INT_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_FE_INT_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_NRE_INT_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_ISFE_INT_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_CE_INT_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_PBE_INT_BIT_LEN (1)
#define TMS570_SCI_SET_INT_SET_BE_INT_BIT_LEN (1)



/* CLEAR_INT Fields */
#define TMS570_SCI_CLEAR_INT_CLEAR_BRKDT_INT_OFFSET (0)
#define TMS570_SCI_CLEAR_INT_CLEAR_WAKEUP_INT_OFFSET (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_TIMEOUT_INT_OFFSET (4)
#define TMS570_SCI_CLEAR_INT_CLEAR_TOAWUS_INT_OFFSET (6)
#define TMS570_SCI_CLEAR_INT_CLEAR_TOA3WUS_INT_OFFSET (7)
#define TMS570_SCI_CLEAR_INT_CLEAR_TX_INT_OFFSET (8)
#define TMS570_SCI_CLEAR_INT_CLEAR_RX_INT_OFFSET (9)
#define TMS570_SCI_CLEAR_INT_CLEAR_ID_INT_OFFSET (13)
#define TMS570_SCI_CLEAR_INT_CLEAR_TX_DMA_OFFSET (16)
#define TMS570_SCI_CLEAR_INT_CLEAR_RX_DMA_OFFSET (17)
#define TMS570_SCI_CLEAR_INT_CLEAR_RX_DMA_ALL_OFFSET (18)
#define TMS570_SCI_CLEAR_INT_CLEAR_PE_INT_OFFSET (24)
#define TMS570_SCI_CLEAR_INT_CLEAR_OE_INT_OFFSET (25)
#define TMS570_SCI_CLEAR_INT_CLEAR_FE_INT_OFFSET (26)
#define TMS570_SCI_CLEAR_INT_CLEAR_NRE_INT_OFFSET (27)
#define TMS570_SCI_CLEAR_INT_CLEAR_ISFE_INT_OFFSET (28)
#define TMS570_SCI_CLEAR_INT_CLEAR_CE_INT_OFFSET (29)
#define TMS570_SCI_CLEAR_INT_CLEAR_PBE_INT_OFFSET (30)
#define TMS570_SCI_CLEAR_INT_CLEAR_BE_INT_OFFSET (31)

#define TMS570_SCI_CLEAR_INT_CLEAR_BRKDT_INT_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_WAKEUP_INT_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_TIMEOUT_INT_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_TOAWUS_INT_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_TOA3WUS_INT_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_TX_INT_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_RX_INT_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_ID_INT_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_TX_DMA_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_RX_DMA_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_RX_DMA_ALL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_PE_INT_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_OE_INT_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_FE_INT_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_NRE_INT_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_ISFE_INT_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_CE_INT_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_PBE_INT_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_CLEAR_BE_INT_BIT_LEN (1)

/* SET_INT_LVL Fields */
#define TMS570_SCI_SET_INT_LVL_SET_BRKDT_INT_LVL_OFFSET (0)
#define TMS570_SCI_SET_INT_LVL_SET_WAKEUP_INT_LVL_OFFSET (1)
#define TMS570_SCI_SET_INT_LVL_SET_TIMEOUT_INT_LVL_OFFSET (4)
#define TMS570_SCI_SET_INT_LVL_SET_TOAWUS_INT_LVL_OFFSET (6)
#define TMS570_SCI_SET_INT_LVL_SET_TOA3WUS_INT_LVL_OFFSET (7)
#define TMS570_SCI_SET_INT_LVL_SET_TX_INT_LVL_OFFSET (8)
#define TMS570_SCI_SET_INT_LVL_SET_RX_INT_LVL_OFFSET (9)
#define TMS570_SCI_SET_INT_LVL_SET_ID_INT_LVL_OFFSET (13)
#define TMS570_SCI_SET_INT_LVL_SET_RX_DMA_ALL_LVL_OFFSET (18)
#define TMS570_SCI_SET_INT_LVL_SET_PE_INT_LVL_OFFSET (24)
#define TMS570_SCI_SET_INT_LVL_SET_OE_INT_LVL_OFFSET (25)
#define TMS570_SCI_SET_INT_LVL_SET_FE_INT_LVL_OFFSET (26)
#define TMS570_SCI_SET_INT_LVL_SET_NRE_INT_LVL_OFFSET (27)
#define TMS570_SCI_SET_INT_LVL_SET_ISFE_INT_LVL_OFFSET (28)
#define TMS570_SCI_SET_INT_LVL_SET_CE_INT_LVL_OFFSET (29)
#define TMS570_SCI_SET_INT_LVL_SET_PBE_INT_LVL_OFFSET (30)
#define TMS570_SCI_SET_INT_LVL_SET_BE_INT_LVL_OFFSET (31)

#define TMS570_SCI_SET_INT_LVL_SET_BRKDT_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_WAKEUP_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_TIMEOUT_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_TOAWUS_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_TOA3WUS_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_TX_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_RX_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_ID_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_TX_DMA_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_RX_DMA_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_RX_DMA_ALL_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_PE_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_OE_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_FE_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_NRE_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_ISFE_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_CE_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_PBE_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_SET_INT_LVL_SET_BE_INT_LVL_BIT_LEN (1)

/* CLEAR_INT_LVL Fields */
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_BRKDT_INT_LVL_OFFSET (0)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_WAKEUP_INT_LVL_OFFSET (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_TIMEOUT_INT_LVL_OFFSET (4)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_TOAWUS_INT_LVL_OFFSET (6)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_TOA3WUS_INT_LVL_OFFSET (7)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_TX_INT_LVL_OFFSET (8)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_RX_INT_LVL_OFFSET (9)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_ID_INT_LVL_OFFSET (13)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_RX_DMA_ALL_LVL_OFFSET (18)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_PE_INT_LVL_OFFSET (24)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_OE_INT_LVL_OFFSET (25)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_FE_INT_LVL_OFFSET (26)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_NRE_INT_LVL_OFFSET (27)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_ISFE_INT_LVL_OFFSET (28)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_CE_INT_LVL_OFFSET (29)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_PBE_INT_LVL_OFFSET (30)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_BE_INT_LVL_OFFSET (31)

#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_BRKDT_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_WAKEUP_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_TIMEOUT_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_TOAWUS_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_TOA3WUS_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_TX_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_RX_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_ID_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_TX_DMA_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_RX_DMA_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_RX_DMA_ALL_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_PE_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_OE_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_FE_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_NRE_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_ISFE_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_CE_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_PBE_INT_LVL_BIT_LEN (1)
#define TMS570_SCI_CLEAR_INT_LVL_CLEAR_BE_INT_LVL_BIT_LEN (1)

/* FLR Fields */
#define TMS570_SCI_FLR_BRKDT_OFFSET (0)
#define TMS570_SCI_FLR_WAKEUP_OFFSET (1)
#define TMS570_SCI_FLR_IDLE_OFFSET (2)
#define TMS570_SCI_FLR_BUSY_OFFSET (3)
#define TMS570_SCI_FLR_TIMEOUT_OFFSET (4)
#define TMS570_SCI_FLR_TOAWUS_OFFSET (6)
#define TMS570_SCI_FLR_TOA3WUS_OFFSET (7)
#define TMS570_SCI_FLR_TX_RDY_OFFSET (8)
#define TMS570_SCI_FLR_RX_RDY_OFFSET (9)
#define TMS570_SCI_FLR_TX_WAKE_OFFSET (10)
#define TMS570_SCI_FLR_TX_EMPTY_OFFSET (11)
#define TMS570_SCI_FLR_RX_WAKE_OFFSET (12)
#define TMS570_SCI_FLR_ID_TX_OFFSET (13)
#define TMS570_SCI_FLR_ID_RX_OFFSET (14)
#define TMS570_SCI_FLR_PE_OFFSET (24)
#define TMS570_SCI_FLR_OE_OFFSET (25)
#define TMS570_SCI_FLR_FE_OFFSET (26)
#define TMS570_SCI_FLR_NRE_OFFSET (27)
#define TMS570_SCI_FLR_ISFE_OFFSET (28)
#define TMS570_SCI_FLR_CE_OFFSET (29)
#define TMS570_SCI_FLR_PBE_OFFSET (30)
#define TMS570_SCI_FLR_BE_OFFSET (31)

#define TMS570_SCI_FLR_BRKDT_BIT_LEN (1)
#define TMS570_SCI_FLR_WAKEUP_BIT_LEN (1)
#define TMS570_SCI_FLR_IDLE_BIT_LEN (1)
#define TMS570_SCI_FLR_BUSY_BIT_LEN (1)
#define TMS570_SCI_FLR_TIMEOUT_BIT_LEN (1)
#define TMS570_SCI_FLR_TOAWUS_BIT_LEN (1)
#define TMS570_SCI_FLR_TOA3WUS_BIT_LEN (1)
#define TMS570_SCI_FLR_TX_RDY_BIT_LEN (1)
#define TMS570_SCI_FLR_RX_RDY_BIT_LEN (1)
#define TMS570_SCI_FLR_TX_WAKE_BIT_LEN (1)
#define TMS570_SCI_FLR_TX_EMPTY_BIT_LEN (1)
#define TMS570_SCI_FLR_RX_WAKE_BIT_LEN (1)
#define TMS570_SCI_FLR_ID_TX_BIT_LEN (1)
#define TMS570_SCI_FLR_ID_RX_BIT_LEN (1)
#define TMS570_SCI_FLR_PE_BIT_LEN (1)
#define TMS570_SCI_FLR_OE_BIT_LEN (1)
#define TMS570_SCI_FLR_FE_BIT_LEN (1)
#define TMS570_SCI_FLR_NRE_BIT_LEN (1)
#define TMS570_SCI_FLR_ISFE_BIT_LEN (1)
#define TMS570_SCI_FLR_CE_BIT_LEN (1)

/* INT_VECT_0 Fields */
#define TMS570_SCI_INT_VECT_0_INT_VECT_0_OFFSET (0)

#define TMS570_SCI_INT_VECT_0_BIT_LEN (5)

/* INT_VECT_1 Fields */
#define TMS570_SCI_INT_VECT_1_INT_VECT_1_OFFSET (0)

#define TMS570_SCI_INT_VECT_1_BIT_LEN (5)

/* FORMAT Fields */
#define TMS570_SCI_FORMAT_CHAR_OFFSET (0)
#define TMS570_SCI_FORMAT_LENGTH_OFFSET (16)

#define TMS570_SCI_FORMAT_CHAR_BIT_LEN (3)
#define TMS570_SCI_FORMAT_LENGTH_BIT_LEN (3)

/* BRS Fields */
#define TMS570_SCI_BRS_PRESCALER_P_OFFSET (0)
#define TMS570_SCI_BRS_M_OFFSET (24)
#define TMS570_SCI_BRS_U_OFFSET (28)

#define TMS570_SCI_BRS_PRESCALER_P_BIT_LEN (24)
#define TMS570_SCI_BRS_M_BIT_LEN (4)
#define TMS570_SCI_BRS_U_BIT_LEN (3)

/* ED Fields */
#define TMS570_SCI_ED_ED_OFFSET (0)
#define TMS570_SCI_ED_ED_BIT_LEN (8)

/* RD Fields */
#define TMS570_SCI_RD_RD_OFFSET (0)
#define TMS570_SCI_RD_RD_BIT_LEN (8)

/* TD Fields */
#define TMS570_SCI_TD_TD_OFFSET (0)
#define TMS570_SCI_TD_TD_BIT_LEN (8)

/* PIO_0 Fields */
#define TMS570_SCI_PIO_0_RX_FUNC_OFFSET (1)
#define TMS570_SCI_PIO_0_TX_FUNC_OFFSET (2)

#define TMS570_SCI_PIO_0_RX_FUNC_BIT_LEN (1)
#define TMS570_SCI_PIO_0_TX_FUNC_BIT_LEN (1)

/* PIO_1 Fields */
#define TMS570_SCI_PIO_1_RX_DIR_OFFSET (1)
#define TMS570_SCI_PIO_1_TX_DIR_OFFSET (2)

#define TMS570_SCI_PIO_1_RX_DIR_BIT_LEN (1)
#define TMS570_SCI_PIO_1_TX_DIR_BIT_LEN (1)

/* PIO_2 Fields */
#define TMS570_SCI_PIO_2_RX_IN_OFFSET (1)
#define TMS570_SCI_PIO_2_TX_IN_OFFSET (2)

#define TMS570_SCI_PIO_2_RX_IN_BIT_LEN (1)
#define TMS570_SCI_PIO_2_TX_IN_BIT_LEN (1)

/* PIO_3 Fields */
#define TMS570_SCI_PIO_3_RX_OUT_OFFSET (1)
#define TMS570_SCI_PIO_3_TX_OUT_OFFSET (2)

#define TMS570_SCI_PIO_3_RX_OUT_BIT_LEN (1)
#define TMS570_SCI_PIO_3_TX_OUT_BIT_LEN (1)

/* PIO_4 Fields */
#define TMS570_SCI_PIO_4_RX_SET_OFFSET (1)
#define TMS570_SCI_PIO_4_TX_SET_OFFSET (2)

#define TMS570_SCI_PIO_4_RX_SET_BIT_LEN (1)
#define TMS570_SCI_PIO_4_TX_SET_BIT_LEN (1)

/* PIO_5 Fields */
#define TMS570_SCI_PIO_5_RX_CLR_OFFSET (1)
#define TMS570_SCI_PIO_5_TX_CLR_OFFSET (2)

#define TMS570_SCI_PIO_5_RX_CLR_BIT_LEN (1)
#define TMS570_SCI_PIO_5_TX_CLR_BIT_LEN (1)

/* PIO_6 Fields */
#define TMS570_SCI_PIO_6_RX_PDR_OFFSET (1)
#define TMS570_SCI_PIO_6_TX_PDR_OFFSET (2)

#define TMS570_SCI_PIO_6_RX_PDR_BIT_LEN (1)
#define TMS570_SCI_PIO_6_TX_PDR_BIT_LEN (1)

/* PIO_7 Fields */
#define TMS570_SCI_PIO_7_RX_PD_OFFSET (1)
#define TMS570_SCI_PIO_7_TX_PD_OFFSET (2)

#define TMS570_SCI_PIO_7_RX_PD_BIT_LEN (1)
#define TMS570_SCI_PIO_7_TX_PD_BIT_LEN (1)

/* PIO_8 Fields */
#define TMS570_SCI_PIO_8_RX_PSL_OFFSET (1)
#define TMS570_SCI_PIO_8_TX_PSL_OFFSET (2)

#define TMS570_SCI_PIO_8_RX_PSL_BIT_LEN (1)
#define TMS570_SCI_PIO_8_TX_PSL_BIT_LEN (1)

/* LIN_COMPARE Fields */
#define TMS570_LIN_COMPARE_SBREAK_OFFSET (0)
#define TMS570_LIN_COMPARE_SDEL_OFFSET (8)

#define TMS570_LIN_COMPARE_SBREAK_BIT_LEN (3)
#define TMS570_LIN_COMPARE_SDEL_BIT_LEN (2)

/* LIN_RD_0 Fields */
#define TMS570_LIN_RD_0_RD_3_OFFSET (0)
#define TMS570_LIN_RD_0_RD_2_OFFSET (8)
#define TMS570_LIN_RD_0_RD_1_OFFSET (16)
#define TMS570_LIN_RD_0_RD_0_OFFSET (24)

#define TMS570_LIN_RD_0_RD_3_BIT_LEN (8)
#define TMS570_LIN_RD_0_RD_2_BIT_LEN (8)
#define TMS570_LIN_RD_0_RD_1_BIT_LEN (8)
#define TMS570_LIN_RD_0_RD_0_BIT_LEN (8)

/* LIN_RD_1 Fields */
#define TMS570_LIN_RD_1_RD_7_OFFSET (0)
#define TMS570_LIN_RD_1_RD_6_OFFSET (8)
#define TMS570_LIN_RD_1_RD_5_OFFSET (16)
#define TMS570_LIN_RD_1_RD_4_OFFSET (24)

#define TMS570_LIN_RD_1_RD_7_BIT_LEN (8)
#define TMS570_LIN_RD_1_RD_6_BIT_LEN (8)
#define TMS570_LIN_RD_1_RD_5_BIT_LEN (8)
#define TMS570_LIN_RD_1_RD_4_BIT_LEN (8)

/* LIN_MASK Fields */
#define TMS570_LIN_MASK_TX_ID_MASK_OFFSET (0)
#define TMS570_LIN_MASK_RX_ID_MASK_OFFSET (16)

#define TMS570_LIN_MASK_TX_ID_MASK_BIT_LEN (8)
#define TMS570_LIN_MASK_RX_ID_MASK_BIT_LEN (8)

/* LIN_ID Fields */
#define TMS570_LIN_ID_ID_BYTE_OFFSET (0)
#define TMS570_LIN_ID_ID_SlaveTask_BYTE_OFFSET (8)
#define TMS570_LIN_ID_RECEIVER_ID_OFFSET (16)

#define TMS570_LIN_ID_ID_BYTE_BIT_LEN (8)
#define TMS570_LIN_ID_ID_SlaveTask_BYTE_BIT_LEN (8)
#define TMS570_LIN_ID_RECEIVER_ID_BIT_LEN (8)

/* LIN_TD_0 Fields */
#define TMS570_LIN_TD_0_TD_3_OFFSET (0)
#define TMS570_LIN_TD_0_TD_2_OFFSET (8)
#define TMS570_LIN_TD_0_TD_1_OFFSET (16)
#define TMS570_LIN_TD_0_TD_0_OFFSET (24)

#define TMS570_LIN_TD_0_TD_3_BIT_LEN (8)
#define TMS570_LIN_TD_0_TD_2_BIT_LEN (8)
#define TMS570_LIN_TD_0_TD_1_BIT_LEN (8)
#define TMS570_LIN_TD_0_TD_0_BIT_LEN (8)

/* LIN_TD_1 Fields */
#define TMS570_LIN_TD_1_TD_7_OFFSET (0)
#define TMS570_LIN_TD_1_TD_6_OFFSET (8)
#define TMS570_LIN_TD_1_TD_5_OFFSET (16)
#define TMS570_LIN_TD_1_TD_4_OFFSET (24)

#define TMS570_LIN_TD_1_TD_7_BIT_LEN (8)
#define TMS570_LIN_TD_1_TD_6_BIT_LEN (8)
#define TMS570_LIN_TD_1_TD_5_BIT_LEN (8)
#define TMS570_LIN_TD_1_TD_4_BIT_LEN (8)

/* MBRS Fields */
#define TMS570_MBRS_MBRS_OFFSET (0)

#define TMS570_MBRS_MBRS_BIT_LEN (13)

/*Input/Output Error Enable Fields*/
#define TMS570_IODFTCTRL_RXP_ENA_OFFSET (0)
#define TMS570_IODFTCTRL_LPB_ENA_OFFSET (1)
#define TMS570_IODFTCTRL_IODFTENA_OFFSET (8)
#define TMS570_IODFTCTRL_TX_SHIFT_OFFSET (16)
#define TMS570_IODFTCTRL_PIN_SAMPLE_MASK_OFFSET (19)
#define TMS570_IODFTCTRL_BRKDT_ENA_OFFSET (24)
#define TMS570_IODFTCTRL_PEN_OFFSET (25)
#define TMS570_IODFTCTRL_FEN_OFFSET (26)
#define TMS570_IODFTCTRL_ISFE_OFFSET (28)
#define TMS570_IODFTCTRL_CEN_OFFSET (29)
#define TMS570_IODFTCTRL_PBEN_OFFSET (30)
#define TMS570_IODFTCTRL_BEN_OFFSET (31)

#define TMS570_IODFTCTRL_RXP_ENA_BIT_LEN (1)
#define TMS570_IODFTCTRL_LPB_ENA_BIT_LEN (1)
#define TMS570_IODFTCTRL_IODFTENA_BIT_LEN (4)
#define TMS570_IODFTCTRL_TX_SHIFT_BIT_LEN (3)
#define TMS570_IODFTCTRL_PIN_SAMPLE_MASK_BIT_LEN (2)
#define TMS570_IODFTCTRL_BRKDT_ENA_BIT_LEN (1)
#define TMS570_IODFTCTRL_PEN_BIT_LEN (1)
#define TMS570_IODFTCTRL_FEN_BIT_LEN (1)
#define TMS570_IODFTCTRL_ISFE_BIT_LEN (1)
#define TMS570_IODFTCTRL_CEN_BIT_LEN (1)
#define TMS570_IODFTCTRL_PBEN_BIT_LEN (1)
#define TMS570_IODFTCTRL_BEN_BIT_LEN (1)


#endif // UART_REGS_H
